name: netos_app
description: 地微

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.5

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^3.0.8
  cupertino_icons: ^0.1.3
  charts_flutter: ^0.8.1
  flutter_screenutil: ^0.7.0
  font_awesome_flutter: ^8.5.0
  qrscan: ^0.2.17
  #生成二维码
  qr_flutter: ^3.2.0
  share: ^0.6.4
  #接收分享
  receive_sharing_intent: ^1.4.0+2
  path_provider: ^1.5.1
  lpinyin: ^1.0.7
  #数据持久化
  shared_preferences: ^0.5.6
  yaml: ^2.2.0
  image_picker: ^0.6.7+12
  photo_view: ^0.10.2
  cached_network_image: ^2.0.0
  transparent_image: ^1.0.0
  #截图
  image_crop: ^0.3.2
  webview_flutter: ^0.3.18+1
  video_player: ^0.10.5
  awsome_video_player: ^1.0.8+1
  flutter_k_chart:
    path: flutter_k_chart
  #  k_chart: ^0.1.1
  floor: ^0.9.0
  common_utils: ^1.1.3
  uuid: ^2.0.4
  badges: ^1.1.0
  #高德定位依赖
  permission_handler: ^4.3.0
  amap_location_fluttify: ^0.8.11+481e45c
  amap_search_fluttify: ^0.7.9+481e45c
  amap_map_fluttify: ^0.18.2+c038d50
  extended_text_field: ^4.0.0
  #已将源码拷到工程
  #  w_popup_menu: ^0.3.0
  popup_menu: ^1.0.5
  flutter_easyrefresh: ^2.0.8
  flutter_plugin_record: ^0.1.3
  just_audio: ^0.0.6
  flutter_slidable: ^0.5.4
  device_info: ^0.4.1+4
  objectdb: ^1.0.7+1
  flutter_animation_progress_bar: ^1.0.0
  framework:
    path: framework
  #九宫格头像
  nineold:
    path: flutter_nineold
  #微信分享、支付插件
  fluwx: ^2.1.0
  #alipay插件
  tobias: ^1.6.1
  #保存图片到相册
  image_gallery_saver: ^1.2.2
  city_pickers: ^0.1.30
  #flutter_cupertino_date_picker: ^1.0.26+2
  flutter_cupertino_date_picker:
    path: flutter-cupertino-date-picker
  toast: ^0.1.5
  synchronized: ^2.2.0+2
  #扫银行卡,注意：插件启动有错，在android下修改了build.gradle文件，添加：1。ext.kotlin_version="1.3.30"；2。 classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  #且将minSdkVersion从19提升至21，即安卓5.0以上
#  card_scanner: ^0.1.0+1
  #视频压缩
  flutter_video_compress: ^0.3.7+8
  package_info: ^0.4.3
  open_file:
    path: open_file
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.9.0
  build_runner: ^1.7.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - lib/portals/gbera/images/gbera.png
    - lib/portals/gbera/images/gbera_bk.png
    - lib/portals/gbera/images/gbera_op.png
    - lib/portals/gbera/images/entrypoint_bk.jpg
    - lib/portals/gbera/images/netflow.png
    - lib/portals/gbera/images/penquan.png
    - lib/portals/gbera/images/yuanbao.png
    - lib/portals/gbera/images/avatar.png
    - lib/portals/gbera/images/default_avatar.png
    - lib/portals/gbera/images/default_image.png
    - lib/portals/gbera/data/user_constract
    - lib/portals/gbera/data/portlets.json
    - lib/portals/gbera/data/portlet_defaults.json
    - lib/portals/gbera/wallpapers/wallpapper.yaml
    - lib/portals/gbera/wallpapers/1.jpeg
    - lib/portals/gbera/wallpapers/2.jpeg
    - lib/portals/gbera/wallpapers/3.jpeg
    - lib/portals/gbera/wallpapers/4.jpeg
    - lib/portals/gbera/wallpapers/5.jpeg
    - lib/portals/gbera/wallpapers/6.png
    - lib/portals/gbera/data/depth.json
    - lib/portals/gbera/data/kline.json
    - lib/portals/gbera/images/cat-green.gif
    - lib/portals/gbera/images/cat-red.gif
    - lib/portals/gbera/images/cat-grey.gif
    - lib/portals/gbera/images/default_watting.gif
    - lib/portals/nodepower/assets/wybank_config_template.yaml

  fonts:
    - family: geo_discovery
      fonts:
        - asset: lib/portals/gbera/fonts/geo_discovery.ttf
    - family: geo_navigation
      fonts:
        - asset: lib/portals/gbera/fonts/geo_navigation.ttf
    - family: geo_locations
      fonts:
        - asset: lib/portals/gbera/fonts/geo_locations.ttf
    - family: market
      fonts:
        - asset: lib/portals/gbera/fonts/market.ttf
    - family: market_shishang
      fonts:
        - asset: lib/portals/gbera/fonts/market_shishang.ttf
    - family: netflow
      fonts:
        - asset: lib/portals/gbera/fonts/netflow.ttf
    - family: netflow2
      fonts:
        - asset: lib/portals/gbera/fonts/netflow_2.ttf
    - family: ellipse
      fonts:
        - asset: lib/portals/gbera/fonts/ellipse.ttf
    - family: chats
      fonts:
        - asset: lib/portals/gbera/fonts/chats.ttf
    - family: absorber
      fonts:
        - asset: lib/portals/gbera/fonts/absorber.ttf